name: nixpkgs review

on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'Pull request'
        required: true
        type: number

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  review:
    runs-on: ubuntu-latest
    name: Review nixpkgs "# ${{ inputs.pr }}"

    steps:
    - name: Checkout NixOS/nixpkgs
      uses: actions/checkout@v3
      with:
        repository: NixOS/nixpkgs
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Print nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - uses: cachix/cachix-action@v12
      with:
        name: tarc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community,kclejeune,tarc
    - uses: workflow/nix-shell-action@v3
      with:
        packages: hello
        script: |
          hello
